version: '3.7'

services:
    backend:
      image: k3ateam/k3a-backend:1.0
      container_name: backend
      command: sh -c "uvicorn main:app --port=8000 --host 0.0.0.0"
      ports:
        - "8000:8000"
      env_file:
        - ../../.env
      
    nginx:
      image: nginx:latest
      container_name: nginx
      volumes:
        - ../../conf/nginx.conf:/etc/nginx/nginx.conf
        - certbot_conf:/etc/letsencrypt
        - certbot_www:/var/www/certbot
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - backend

    certbot:
      image: certbot/certbot
      container_name: certbot
      volumes: 
        - certbot_conf:/etc/letsencrypt
        - certbot_www:/var/www/certbot
      command: certonly -v -n --agree-tos --webroot -w /var/www/certbot --email ${CERTBOT_EMAIL} -d api.cognifile.org
      env_file:
        - ../../.env

volumes:
  certbot_conf:
  certbot_www: