version: '3.7'

services:
    backend:
      image: k3ateam/k3a-backend:1.0
      container_name: backend
      command: sh -c "uvicorn main:app --port=8000 --host 0.0.0.0"
      ports:
        - "8000:8000"
      env_file:
        - ../../.env

    nginx:
      image: nginx:latest
      container_name: nginx
      restart: unless-stopped
      command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
      volumes:
        - ../../conf/nginx.conf:/etc/nginx/nginx.conf
        - ../../conf/.htpasswd:/etc/nginx/.htpasswd
        - ./data/certbot/conf:/etc/letsencrypt
        - ./data/certbot/www:/var/www/certbot
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - backend

    certbot:
      image: certbot/certbot:latest
      container_name: certbot
      volumes:
        - ./data/certbot/conf:/etc/letsencrypt
        - ./data/certbot/www:/var/www/certbot
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
