version: '3.7'

services:
    backend:
      image: k3ateam/k3a-backend:1.0
      container_name: backend
      command: sh -c "uvicorn main:app --port=8000 --host 0.0.0.0"
      ports:
        - "8000:8000"
      env_file:
        - ../../.env
      
    nginx:
      image: nginx:latest
      container_name: nginx
      restart: unless-stopped
      volumes:
        - ../../conf/nginx.conf:/etc/nginx/nginx.conf
        - ../../certbot/conf:/etc/letsencrypt
        - ../../certbot/www:/var/www/certbot
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - backend

    certbot:
      image: certbot/certbot
      container_name: certbot
      volumes: 
        - ../../certbot/conf:/etc/letsencrypt
        - ../../certbot/www:/var/www/certbot
      command: certonly --nginx --webroot -w /var/www/certbot --force-renewal --email allaouaokba@gmail.com --domains api.cognifile.org --non-interactive --agree-tos
      env_file:
        - ../../.env
