version: '3.7'

services:
    backend:
      image: k3ateam/k3a-backend:1.0
      command: sh-c"uvicorn main:app --port=8000 --host 0.0.0.0"
      ports:
        - "8000:8000"
      env_file:
        - ../../.env
      
    nginx:
      image: nginx:latest
      volumes:
        - ../../conf/nginx.conf:/etc/nginx/nginx.conf
        - ../../ssl:/etc/nginx/ssl
      ports:
        - "443:443"
      depends_on:
        - backend
