name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Setup environment files
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
        echo "${{ secrets.FIREBASE_CONFIG }}" > firebase.json

    - name: Build and push Docker image
      run: |
        docker build -t k3ateam/k3a-backend:1.0 .
        docker push k3ateam/k3a-backend:1.0

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.10.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Setup environment files
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
        echo "${{ secrets.FIREBASE_CONFIG }}" > firebase.json

    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }}
        cd /opt/CogniFile-backend &&
        git pull origin main &&
        docker pull k3ateam/k3a-backend:1.0 &&
        docker-compose down &&
        docker-compose up -d"
